accounts/urls.py
from django.urls import path
from .views import SignUpView


app_name = "accounts"

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup"),
]

produk/urls.py
from django.urls import path
from .views import (IndexProductView, DetailProductView,
                    DetailStationery, filter)


app_name = "produk"

urlpatterns = [
    path('', IndexProductView.as_view(), name='index'),
    path('<str:c>/', filter, name='filter'),
    path('buku/<int:pk>/<slug:slug>/',
         DetailProductView.as_view(), name='detail-buku'),
    path('stationery/<int:pk>/<slug:slug>/',
         DetailStationery.as_view(), name='detail-stationery'),
]

toko_buku/urls.py
from django.contrib import admin
from django.urls import path, include
from produk.views import (AuthorListView, AuthorDetailView,
                          PublisherListView, PublisherDetailView, SearchResultView)
from .views import IndexHomePagesViews


urlpatterns = [
    path('', IndexHomePagesViews.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('penulis/<page>/', AuthorListView.as_view(), name="penulis"),
    path('penulis/<int:pk>/<slug:slug>',
         AuthorDetailView.as_view(), name="writer_detail"),
    path('penerbit/<page>/', PublisherListView.as_view(), name="penerbit"),
    path('penerbit/<int:pk>/<slug:slug>',
         PublisherDetailView.as_view(), name="publisher_detail"),
    path('produk/', include("produk.urls", namespace="produk")),
    path('search/', SearchResultView.as_view(), name="search_result"),
]

templates/snippets/footer.html
{% load static %}

<footer class="text-center text-lg-start bg-primary text-white" style="margin-top: 200px;">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
            <span>Toko buku online terlengkap dan terpercaya di sini. Unduh aplikasinya :</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
            <a href="https://play.google.com/store/games?device=windows" target="_blank">
                <img src="{% static 'icon/badge_googleplay.png' %}" alt="GooglePlay" style="width: 34%;">
            </a>
            <a href="https://www.apple.com/id/app-store/" target="_blank">
                <img src="{% static 'icon/badge_iOS.png' %}" alt="AppStore">
            </a>
        </div>
        <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
        <div class="container text-center text-md-start mt-5">
            <!-- Grid row -->
            <div class="row mt-3">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">PT. Toko Buku Online</h6>
                <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">Produk</h6>
                <p><a href="{% url 'produk:filter' c='buku' %}" class="text-reset">Buku</a></p>
                <p><a href="{% url 'produk:filter' c='stationery' %}" class="text-reset">Stationery</a></p>
                <p><a href="#!" class="text-reset">Majalah dan Buletin</a></p>
                <p><a href="#!" class="text-reset">Voucher Edukasi</a></p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">Tentang Kami</h6>
                <p><a href="#!" class="text-reset">Profil Perusahaan</a></p>
                <p><a href="#!" class="text-reset">Syarat & Ketentuan</a></p>
                <p><a href="#!" class="text-reset">Kebijakan & Privasi</a></p>
                <p><a href="#!" class="text-reset">Bantuan</a></p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">Hubungi Kami</h6>
                <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                <p><i class="fas fa-envelope me-3"></i>info@example.com</p>
                <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </section>
    <!-- Section: Links  -->

    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 26, 255, 0.575)">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
</footer>

templates/snippets/jumbotron.html
{% load static %}

<div
    class="jumbotron jumbotron-fluid"
    id="jumbotron"
    style="
        background-image: url(../../static/icon/main-header.jpg);
        background-position: center;
        background-size: cover;
        height: 600px;">
    <div
        class="container text-white text-center"
        style="padding-top: 200px;
            padding-bottom: 205px;
            background-color: rgba(0, 0, 0, 0.4);">
        <h1 class="display-4">Toko Buku Online</h1>
        <span class="lead">
            <q>Cuma perlu satu buku untuk jatuh cinta pada membaca.<br>Cari buku itu. Mari jatuh cinta.</q>
            <br><br>~ Najwa Shihab
        </span>
    </div>
</div>

templates/snippets/modal.html
<!-- Bootstrap Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            {% if user.is_authenticated %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Buy this book?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Hello, {{user.username}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            {% else %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">You haven't already login!</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Untuk membeli buku ini, Anda perlu <a href="{% url 'login' %}">login</a> dengan akun Anda.</p>
                    <p>Belum punya akun? Silahkan mendaftar akun baru <a href="{% url 'accounts:signup' %}">disini</a></p>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Bootstrap Modal -->

templates/snippets/navbar.html
<nav class="navbar bg-primary navbar-expand-lg" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">OnlineBookStore</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Beranda</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link active" href="{% url 'produk:index' %}">Produk</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'produk:index' %}" class="dropdown-item">Semua Produk</a></li>
                        <li><a href="{% url 'produk:filter' c='buku' %}" class="dropdown-item">Buku</a></li>
                        <li><a href="{% url 'produk:filter' c='stationery' %}" class="dropdown-item">Stationery</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Mitra Kami
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'penulis' 1 %}">Penulis</a></li>
                        <li><a class="dropdown-item" href="{% url 'penerbit' 1 %}">Penerbit</a></li>
                    </ul>
                </li>
            </ul>
            <!-- Kolom pencarian -->
            <form action="{% url 'search_result' %}" method="get" class="d-flex" role="search" style="padding-right: 50px;">
                <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-dark" type="submit">Search</button>
            </form>
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{user.username}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{#{% url 'profile' username=user.username pk=user.pk %}#}">My Profile</a></li>
                        <li><a class="dropdown-item" href="#">Wishlist</a></li>
                        <li><a class="dropdown-item" href="#">Shop Cart</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link active">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/bootstrap/bootstrap.bundle.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery.js' %}"></script>
<script src="{% static 'vendor/popper/popper.js' %}"></script>
<script src="{% static 'js/form-control.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="shortcut icon" href="{% static 'icon/book.png' %}" />