produk/urls.py
from django.urls import path
from .views import (IndexProductView, DetailProductView,
                    DetailStationery, filter)


app_name = "produk"

urlpatterns = [
    path('', IndexProductView.as_view(), name='index'),
    path('<str:c>/', filter, name='filter'),
    path('buku/<int:pk>/<slug:slug>/',
         DetailProductView.as_view(), name='detail-buku'),
    path('stationery/<int:pk>/<slug:slug>/',
         DetailStationery.as_view(), name='detail-stationery'),
]

toko_buku/urls.py
from django.contrib import admin
from django.urls import path, include
from produk.views import (AuthorListView, AuthorDetailView,
                          PublisherListView, PublisherDetailView, SearchResultView)
from .views import IndexHomePagesViews


urlpatterns = [
    path('', IndexHomePagesViews.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('penulis/<page>/', AuthorListView.as_view(), name="penulis"),
    path('penulis/<int:pk>/<slug:slug>',
         AuthorDetailView.as_view(), name="writer_detail"),
    path('penerbit/<page>/', PublisherListView.as_view(), name="penerbit"),
    path('penerbit/<int:pk>/<slug:slug>',
         PublisherDetailView.as_view(), name="publisher_detail"),
    path('produk/', include("produk.urls", namespace="produk")),
    path('search/', SearchResultView.as_view(), name="search_result"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS Bootstrap template -->
    {% include "snippets/styles.html" %}

    <title>
        {% block page_title %}
            {{website}} | {{halaman}}
        {% endblock page_title %}
    </title>
</head>
<body>
    <!-- Navbar Bootstrap template -->
    {% include "snippets/navbar.html" %}
    
    <!-- Jumbotron Section -->
    {% block jumbotron %}
    {% endblock jumbotron %}
    
    <div class="container pt-5">
        {% block contents %}
        {% endblock contents %}
    </div>

    <!-- BLOCK Manajemen Account -->
    <div class="container">
        {% block login %}
        {% endblock login %}
    </div>

    <div class="container">
        {% block signup_account %}
        {% endblock signup_account %}
    </div>

    <div class="container">
        {% block ganti_password %}
        {% endblock ganti_password %}
    </div>

    <div class="container">
        {% block ganti_password_sukses %}
        {% endblock ganti_password_sukses %}
    </div>

    <div class="container">
        {% block reset_password %}
        {% endblock reset_password %}
    </div>

    <div class="container">
        {% block reset_password_sukses %}
        {% endblock reset_password_sukses %}
    </div>

    <div class="container">
        {% block input_password_baru %}
        {% endblock input_password_baru %}
    </div>
    <div class="container">
        {% block reset_password_complete %}
        {% endblock reset_password_complete %}
    </div>
    <!-- END Manajemen Account -->

    <!-- BLOCK query pencarian data -->
    <div class="container pt-5">
        {% block pencarian %}
        {% endblock pencarian %}
    </div>
    <!-- END query pencarian data -->

    <!-- Footer template -->
    {% include "snippets/footer.html" %}
    
    <!-- JavaScript Bootstrap template -->
    {% include "snippets/scripts.html" %}

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}


{% block jumbotron %}
{% include "snippets/jumbotron.html" %}
{% endblock jumbotron %}

{% block contents %}

<h1 class="pb-3">Buku pilihan</h1>
<div class="row row-cols-5">
    {% for book in books %}
    <div class="col pb-2" style="margin-right: 55px;">
        {% if book.is_discount %}
        <div class="card shadow-sm" style="width: 15rem;">
            <a href="{% url 'produk:detail-buku' book.pk book.slug %}">
                <span class="badge text-bg-danger" style="clip: auto;">{{book.discount}}%</span>
                <img
                    src="{% static 'produk/buku' %}/{{book.sampul_buku}}"
                    class="card-img-top"
                    style="width: 100%; max-height: 250px; object-fit: contain;">
            </a>
            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                <a href="{% url 'produk:detail-buku' book.pk book.slug %}" class="text-decoration-none text-dark">
                    <h6 class="card-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.judul_buku}}</h6>
                </a>
                <span>
                    Rp. <del>{{book.harga|intcomma}}</del> <strong>{{book.harga_diskon|intcomma}}</strong>
                </span>
            </div>
        </div>
        {% else %}
        <div class="card shadow-sm" style="width: 15rem;">
            <a href="{% url 'produk:detail-buku' book.pk book.slug %}">
                <span class="badge" style="clip: auto;">None</span>
                <img
                    src="{% static 'produk/buku' %}/{{book.sampul_buku}}"
                    class="card-img-top"
                    style="width: 100%; max-height: 250px; object-fit: contain;">
            </a>
            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                <a href="{% url 'produk:detail-buku' book.pk book.slug %}" class="text-decoration-none text-dark">
                    <h6 class="card-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.judul_buku}}</h6>
                </a>
                <span>Rp. {{book.harga|intcomma}}</span>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    <div class="container pt-4 pb-4" role="navigation">
        <a href="{% url 'produk:index' %}" class="text-decoration-none">
            <input type="button" value="selengkapnya" class="form-control bg-primary text-white">
        </a>
    </div>
</div>

<!-- Stationery -->

<h1 class="pb-3">Alat Tulis Sekolah / Kantor</h1>
<div class="row row-cols-5">
    {% for s in stationery %}
    <div class="col pb-2" style="margin-right: 55px;">
        {% if s.is_discount %}
        <div class="card shadow-sm" style="width: 15rem;">
            <a href="{% url 'produk:detail-stationery' s.pk s.slug %}">
                <span class="badge text-bg-danger" style="clip: auto;">{{s.discount}}%</span>
                <img
                    src="{% static 'produk/stationery' %}/{{s.gambar_produk}}"
                    class="card-img-top"
                    style="width: 100%; max-height: 250px; object-fit: contain;">
            </a>
            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                <a href="{% url 'produk:detail-stationery' s.pk s.slug %}" class="text-decoration-none text-dark">
                    <h6 class="card-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{s.nama_produk}}</h6>
                </a>
                <span>
                    Rp. <del>{{s.harga|intcomma}}</del> <strong>{{s.harga_diskon|intcomma}}</strong>
                </span>
            </div>
        </div>
        {% else %}
        <div class="card shadow-sm" style="width: 15rem;">
            <a href="{% url 'produk:detail-stationery' s.pk s.slug %}">
                <span class="badge" style="clip: auto;">None</span>
                <img
                    src="{% static 'produk/stationery' %}/{{s.gambar_produk}}"
                    class="card-img-top"
                    style="width: 100%; max-height: 250px; object-fit: contain;">
            </a>
            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                <a href="{% url 'produk:detail-stationery' s.pk s.slug %}" class="text-decoration-none text-dark">
                    <h6 class="card-title" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{s.nama_produk}}</h6>
                </a>
                <span>Rp. {{s.harga|intcomma}}</span>
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    <div class="container pt-4 pb-4" role="navigation">
        <a href="{% url 'produk:index' %}" class="text-decoration-none">
            <input type="button" value="selengkapnya" class="form-control bg-primary text-white">
        </a>
    </div>
</div>
{% endblock contents %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/vendor/bootstrap/bootstrap.css">
    <title>Login</title>
</head>
<body>
    <div class="container pt-5">

        <form method="post">
            <div class="form-group">
                <label for="exampleInputEmail">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter email">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    </div>
    <script src="../static/vendor/bootstrap/bootstrap.bundle.js"></script>
    <script src="../static/vendor/jquery/jquery.js"></script>
</body>
</html>

templates/search.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block page_title %}
Anda mencari {{keyword}}
{% endblock page_title %}

{% block pencarian %}
<div class="container">
    <h1>Hasil pencarian</h1>

    {% if message %}
        <p>{{message}}</p>
    {% else %}
        <p>Hasil pencarian untuk : {{keyword}}</p>

        <div class="row row-cols-5">
            {% for result in search_results %}
                {% if result.type == 'Buku' %}
                    <div class="col pb-2" style="margin-right: 55px;">
                        {% if result.object.is_discount %}
                        <div class="card shadow-sm" style="width: 15rem;">
                            <a href="{% url 'produk:detail-buku' result.object.pk result.object.slug %}">
                                <span class="badge text-bg-danger" style="clip: auto;">{{result.object.discount}}%</span>
                                <img src="{% static 'produk/buku' %}/{{result.object.sampul_buku}}" class="card-img-top" style="width: 100%; max-height: 250px; object-fit: contain;">
                            </a>
                            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                                <a href="{% url 'produk:detail-buku' result.object.pk result.object.slug %}" class="text-dark text-decoration-none">
                                    <h6 class="card-title pb-1" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{result.object.judul_buku}}</h6>
                                </a>
                                <span>
                                    Rp. <del>{{result.object.harga|intcomma}}</del> <strong>{{result.object.harga_diskon|intcomma}}</strong>
                                </span>
                            </div>
                        </div>
                        {% else %}
                        <div class="card shadow-sm" style="width: 15rem;">
                            <a href="{% url 'produk:detail-buku' result.object.pk result.object.slug %}">
                                <span class="badge" style="clip: auto;">None</span>
                                <img src="{% static 'produk/buku' %}/{{result.object.sampul_buku}}" class="card-img-top" style="width: 100%; max-height: 250px; object-fit: contain;">
                            </a>
                            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                                <a href="{% url 'produk:detail-buku' result.object.pk result.object.slug %}" class="text-dark text-decoration-none">
                                    <h6 class="card-title pb-1" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{result.object.judul_buku}}</h6>
                                </a>
                                <span>Rp. {{result.object.harga|intcomma}}</span>
                            </div>
                        </div>
                        {% endif %}
                    </div>
            
                
                {% elif result.type == 'Penulis_Buku' %}
                <div class="col pb-4" style="margin-right: 55px;">
                    <div class="card" style="width: 15rem;">
                        {% if result.object.foto_profil %}
                            <img src="{% static 'produk/penulis' %}/{{result.object.foto_profil}}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                        {% else %}
                            <img src="{% static 'icon/profile-icon.jpg' %}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                        {% endif %}
                        <div class="card-body">
                            <h6><a class="text-decoration-none text-black" href="{% url 'writer_detail' result.object.pk result.object.slug %}">{{result.object.nama_penulis}}</a></h6>
                        </div>
                    </div>
                </div>
                
                {% elif result.type == 'Penerbit_Buku' %}
                <div class="col pb-4" style="margin-right: 55px;">
                    <div class="card" style="width: 15rem;">
                        {% if result.object.logo_penerbit %}
                            <a href="{% url 'publisher_detail' result.object.pk result.object.slug %}">
                                <img src="{% static 'produk/penerbit' %}/{{result.object.logo_penerbit}}"
                                class="card-img-top"
                                style="width: 100%; max-height: 250px; object-fit: contain;">
                            </a>
                            {% else %}
                            <a href="{% url 'publisher_detail' result.object.pk result.object.slug %}">
                                <img src="{% static 'icon/profile-icon.jpg' %}"
                                class="card-img-top"
                                style="width: 100%; max-height: 250px; object-fit: contain;">
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <h6><a class="text-decoration-none text-black" href="{% url 'publisher_detail' result.object.pk result.object.slug %}">{{result.object.penerbit}}</a></h6>
                        </div>
                    </div>
                </div>
                
                {% elif result.type == 'Stationery' %}
                    <div class="col pb-2" style="margin-right: 55px;">
                        {% if result.object.is_discount %}
                        <div class="card shadow-sm" style="width: 15rem;">
                            <a href="{% url 'produk:detail-stationery' result.object.pk result.object.slug %}">
                                <span class="badge text-bg-danger">{{result.object.discount}}%</span>
                                <img src="{% static 'produk/stationery' %}/{{result.object.gambar_produk}}" class="card-img-top" style="width: 100%; max-height: 250px; object-fit: cover;">
                            </a>
                            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                                <h6 class="card-title pb-1" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{result.object.nama_produk}}</h6>
                                <span>
                                    Rp. <del>{{result.object.harga|intcomma}}</del> <strong>{{result.object.harga_diskon|intcomma}}</strong>
                                </span>
                            </div>
                        </div>
                        {% else %}
                        <div class="card shadow-sm" style="width: 15rem;">
                            <a href="{% url 'produk:detail-stationery' result.object.pk result.object.slug %}">
                                <span class="badge">None</span>
                                <img src="{% static 'produk/stationery' %}/{{result.object.gambar_produk}}" class="card-img-top" style="width: 100%; max-height: 250px; object-fit: cover;">
                            </a>
                            <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                                <h6 class="card-title pb-1" style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{result.object.nama_produk}}</h6>
                                <span>Rp. {{result.object.harga|intcomma}}</span>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                
                {% endif %}

            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock pencarian %}

templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/vendor/bootstrap/bootstrap.css">
    <title>Sign Up</title>
</head>
<body>
    <div class="container pt-5">

        <div class="row">
            <div class="col">
                <!-- Kolom untuk widget gambar -->
                <img
                    src="../static/icon/profile-icon.jpg"
                    alt="profile-icon.jpg"
                    style="width: 60%;">
            </div>
            <div class="col">
                <!-- Kolom untuk widget formulir -->
                <form method="post">
                    <div class="form-group pb-3">
                        <label for="firstname">First name</label>
                        <input type="text" id="firstname" class="form-control" placeholder="Nama depan anda">
                    </div>
                    <div class="form-group pb-3">
                        <label for="lastname">Last name</label>
                        <input type="text" id="lastname" class="form-control" placeholder="Nama belakang anda">
                    </div>
                    <div class="form-group pb-3">
                        <label for="email">Email address</label>
                        <input type="email" id="email" class="form-control" placeholder="Email anda">
                        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else</small>
                    </div>
                    <div class="form-group pb-3">
                        <label for="password">Password</label>
                        <input type="password" id="password" class="form-control" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Daftarkan Akun!</button>
                </form>
            </div>
        </div>

    </div>
    <script src="../static/vendor/bootstrap/bootstrap.bundle.js"></script>
    <script src="../static/vendor/jquery/jquery.js"></script>
</body>
</html>